<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE dni [
    <!ELEMENT dni (numero, nombre, apellidos, fecha_nacimiento, nacionalidad, direccion, sexo, fecha_expedicion, fecha_caducidad)>
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT fecha_nacimiento (#PCDATA)>
    <!ELEMENT nacionalidad (#PCDATA)>
    <!ELEMENT direccion (calle, ciudad, provincia, codigo_postal)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
    <!ELEMENT codigo_postal (#PCDATA)>
    <!ELEMENT sexo (#PCDATA)>
    <!ELEMENT fecha_expedicion (#PCDATA)>
    <!ELEMENT fecha_caducidad (#PCDATA)>
]>

<dni>
    <numero>12345678A</numero>
    <nombre>Juan</nombre>
    <apellidos>García López</apellidos>
    <fecha_nacimiento>1985-07-12</fecha_nacimiento>
    <nacionalidad>Española</nacionalidad>
    <direccion>
        <calle>Calle Mayor 123</calle>
        <ciudad>Madrid</ciudad>
        <provincia>Madrid</provincia>
        <codigo_postal>28001</codigo_postal>
    </direccion>
    <sexo>Masculino</sexo>
    <fecha_expedicion>2023-01-15</fecha_expedicion>
    <fecha_caducidad>2033-01-15</fecha_caducidad>
</dni>
