<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE notas [
    <!ELEMENT notas (alumno)>
    <!ELEMENT alumno (nombre, curso, asignaturas)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT curso (#PCDATA)>
    <!ELEMENT asignaturas (asignatura+)>
    <!ELEMENT asignatura (nombreasig, trimestres)>
    <!ELEMENT nombreasig (#PCDATA)>
    <!ELEMENT trimestres (trimestre+)>
    <!ELEMENT trimestre (numero, nota)>
    
    <!-- 3 trimestres -->
    <!ELEMENT numero (#PCDATA)>
    <!ATTLIST numero valor (1|2|3) #REQUIRED>

    <!-- entre 0 y 10 -->
    <!ELEMENT nota (#PCDATA)>
    <!ATTLIST nota valor CDATA #REQUIRED>
]>

<notas>
    <alumno>
        <nombre>Jose Ramon Rejano</nombre>
        <curso>1º DAW</curso>
        <asignaturas>
            <asignatura>
                <nombreasig>Bases de Datos</nombreasig>
                <trimestres>
                    <trimestre>
                        <numero valor="1">1</numero>
                        <nota valor="8.5">8.5</nota>
                    </trimestre>
                    <trimestre>
                        <numero valor="2">2</numero>
                        <nota valor="7.0">7.0</nota>
                    </trimestre>
                    <trimestre>
                        <numero valor="3">3</numero>
                        <nota valor="6.0">6.0</nota>
                    </trimestre>
                </trimestres>
            </asignatura>
            <asignatura>
                <nombreasig>Programación</nombreasig>
                <trimestres>
                    <trimestre>
                        <numero valor="1">1</numero>
                        <nota valor="5.0">5.0</nota>
                    </trimestre>
                    <trimestre>
                        <numero valor="2">2</numero>
                        <nota valor="4.5">4.5</nota>
                    </trimestre>
                    <trimestre>
                        <numero valor="3">3</numero>
                        <nota valor="6.2">6.2</nota>
                    </trimestre>
                </trimestres>
            </asignatura>
        </asignaturas>
    </alumno>
</notas>
