=== javijc96/Lenguajes_2024_Javier_Juarez/segundotrimestre/Tema10/xsd/Ej10estacionmeteorologica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="estacion_meteorologica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ubicacion" type="xs:string"/>
                <xs:element name="fecha" type="xs:date"/>
                <xs:element name="hora" type="xs:string"/>
                <xs:element name="temperatura" type="xs:float"/>
                <xs:element name="humedad" type="xs:int"/>
                <xs:element name="presion" type="xs:int"/>
                <xs:element name="viento">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="direccion" type="xs:string"/>
                            <xs:element name="velocidad" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lluvia" type="xs:float"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== javijc96/Lenguajes_2024_Javier_Juarez/segundotrimestre/Tema10/contenido/Ej10estacionmeteorologica.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE estacion_meteorologica [
<!ELEMENT estacion_meteorologica (ubicacion, fecha, hora, temperatura, humedad, presion, viento, lluvia)>
<!ELEMENT ubicacion (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT temperatura (#PCDATA)>
<!ELEMENT humedad (#PCDATA)>
<!ELEMENT presion (#PCDATA)>
<!ELEMENT viento (direccion, velocidad)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ELEMENT lluvia (#PCDATA)>
]> -->
<estacion_meteorologica    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/Ej10estacionmeteorologica.xsd">
    <ubicacion>Ciudad de MÃ©xico</ubicacion>
    <fecha>2025-02-07</fecha>
    <hora>14:30</hora>
    <temperatura>22.5</temperatura>
    <humedad>65</humedad>
    <presion>1013</presion>
    <viento>
        <direccion>Noroeste</direccion>
        <velocidad>15</velocidad>
    </viento>
    <lluvia>0.2</lluvia>
</estacion_meteorologica>
